In [2]:
import pandas as pd
import numpy as np
import scipy.spatial.distance as sc
import matplotlib.pyplot as plt
import sklearn.metrics as skm
from scipy.cluster import hierarchy

from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs

from sklearn.metrics import pairwise_distances_argmin_min
import seaborn as sb
from mpl_toolkits.mplot3d import Axes3D

pd.core.common.is_list_like = pd.api.types.is_list_like

from datetime import datetime

import matplotlib.image as mpimg
import scipy.optimize as opt

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
from sklearn.metrics import (accuracy_score, precision_score, recall_score)

In [6]:
data = pd.read_excel("../Data/tasa-desempleo-jalisco-2005-2019.xlsx")
data

     Año          Trimestre    Tasa de desocupación
0   2005   Primer trimestre                     3,7
1   2005  Segundo trimestre                     2,9
2   2005   Tercer trimestre                     4,2
3   2005   Cuarto trimestre                     3,4
4   2006   Primer trimestre                     3,9
5   2006  Segundo trimestre                     2,7
6   2006   Tercer trimestre                     3,9
7   2006   Cuarto trimestre                     3,7
8   2007   Primer trimestre                     3,4
9   2007  Segundo trimestre                     2,9
10  2007   Tercer trimestre                     3,4
11  2007   Cuarto trimestre                     3,2
12  2008   Primer trimestre                     3,5
13  2008  Segundo trimestre                       3
14  2008   Tercer trimestre                     3,7
15  2008   Cuarto trimestre                       4
16  2009   Primer trimestre                     5,4
17  2009  Segundo trimestre                     4,4
18  2009   Tercer trimestre                     5,7
19  2009   Cuarto trimestre                     4,9
20  2010   Primer trimestre                     5,2
21  2010  Segundo trimestre                     4,9
22  2010   Tercer trimestre                     5,8
23  2010   Cuarto trimestre                     5,8
24  2011   Primer trimestre                     4,8
25  2011  Segundo trimestre                     5,7
26  2011   Tercer trimestre                     5,5
27  2011   Cuarto trimestre                     5,3
28  2012   Primer trimestre                     4,4
29  2012  Segundo trimestre                     4,6
30  2012   Tercer trimestre                     4,9
31  2012   Cuarto trimestre                     5,4
32  2013   Primer trimestre                     4,4
33  2013  Segundo trimestre                     4,5
34  2013   Tercer trimestre                     5,4
35  2013   Cuarto trimestre                     5,1
36  2014   Primer trimestre                     5,1
37  2014  Segundo trimestre                       5
38  2014   Tercer trimestre                     5,7
39  2014   Cuarto trimestre                     4,9
40  2015   Primer trimestre                       4
41  2015  Segundo trimestre                     5,3
42  2015   Tercer trimestre                     5,2
43  2015   Cuarto trimestre                     4,3
44  2016   Primer trimestre                     4,2
45  2016  Segundo trimestre                     3,7
46  2016   Tercer trimestre                     3,5
47  2016   Cuarto trimestre                     3,3
48  2017   Primer trimestre                     2,7
49  2017  Segundo trimestre                     2,6
50  2017   Tercer trimestre                     3,2
51  2017   Cuarto trimestre                     2,9
52  2018   Primer trimestre                     2,3
53  2018  Segundo trimestre                       3
54  2018   Tercer trimestre                     3,1
55  2018   Cuarto trimestre                     2,5
56  2019   Primer trimestre                     2,6